# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Mitchell Chatterjee — Machine Learning Engineer. Builds production-grade NLP, retrieval, and agentic systems; research in automated cardiovascular arrhythmia detection.'
    twitter: ''
  analytics:
    google_analytics: '' # UA- or G- id (add your id)
    baidu_tongji: ''
    plausible: '' # plausible.io domain
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''
  opengraph:
    # Default OpenGraph image (relative to project root)
    image: assets/media/og-default.svg
    twitter_card: summary_large_image
    # Fallback title/description controlled by page frontmatter where possible
    default_title: 'Mitchell Chatterjee — Machine Learning Engineer'
    default_description: 'Machine Learning Engineer building production-grade NLP, retrieval, and agentic systems. Research in automated cardiovascular arrhythmia detection.'

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Mitchell Chatterjee"

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
