name: Build Hugo site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Required permissions so the deploy step can push to GitHub Pages using the built-in token.
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.135.0'
          extended: true
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build
        env:
          HUGO_ENVIRONMENT: production
        run: |
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
